import React from 'react'
const Main=[{
    id:1,
    Company:"Angelist",
    worktype:"Consultancy",
    post:"datascience",
    location:"anywhere",
    type:"full time",
    jobtype:"remote",
    
    },{
        id:2,
        Company:"intershala",
        worktype:"Intership",
        post:"sales",
        location:"anywhere",
        type:"full time",
        jobtype:"remote", 
    },{
        id:3,
    Company:"Coursify",
    worktype:"Web Development",
    post:"pythondevloper",
    location:"anywhere",
    type:"full time",
    jobtype:"on-site",
    },{
        id:4,
    Company:"Angelist",
    worktype:"Consultancy",
    post:"fullstack",
    location:"anywhere",
    type:"full time",
    jobtype:"remote",
    },{
        id:5,
    Company:"Angelist",
    worktype:"Consultancy",
    post:"fullstack",
    location:"anywhere",
    type:"full time",
    jobtype:"remote",
    },{
        id:6,
    Company:"Angelist",
    worktype:"Consultancy",
    post:"pythondevloper",
    location:"anywhere",
    type:"full time",
    jobtype:"remote",}
    ,{
        id:7,
    Company:"Angelist",
    worktype:"Consultancy",
    post:"datascince",
    location:"anywhere",
    type:"full time",
    jobtype:"remote",
    },{
        id:8,
    Company:"Angelist",
    worktype:"Consultancy",
    post:"investment operation Specialist",
    location:"anywhere",
    type:"full time",
    jobtype:"remote",
    },{
        id:10,
    Company:"Angelist",
    worktype:"Consultancy",
    post:"fullstack",
    location:"anywhere",
    type:"full time",
    jobtype:"remote",
    },{
        id:11,
    Company:"Angelist",
    worktype:"Consultancy",
    post:"sales",
    location:"anywhere",
    type:"full time",
    jobtype:"remote",
    },{
        id:12,
    Company:"Angelist",
    worktype:"Consultancy",
    post:"sales",
    location:"anywhere",
    type:"full time",
    jobtype:"remote",
    },{
        id:13,
    Company:"Angelist",
    worktype:"Consultancy",
    post:"investment operation Specialist",
    location:"anywhere",
    type:"full time",
    jobtype:"remote",
    },{
        id:14,
    Company:"Angelist",
    worktype:"Consultancy",
    post:"pythondevloper",
    location:"anywhere",
    type:"full time",
    jobtype:"remote",
    },{
        id:15,
    Company:"Angelist",
    worktype:"Consultancy",
    post:"investment operation Specialist",
    location:"anywhere",
    type:"full time",
    jobtype:"remote",
    },{
        id:16,
    Company:"Tophire",
    worktype:"Consultancy",
    post:"Fullstake",
    location:"anywhere",
    type:"full time",
    jobtype:"remote",
    },{
        id:17,
    Company:"Topehire",
    worktype:"Consultancy",
    post:"datascience",
    location:"anywhere",
    type:"full time",
    jobtype:"remote",
    },{
        id:18,
    Company:"Angelist",
    worktype:"Consultancy",
    post:"investment operation Specialist",
    location:"anywhere",
    type:"full time",
    jobtype:"remote",
    },{
        id:19,
    Company:"Angelist",
    worktype:"Consultancy",
    post:"datascience",
    location:"anywhere",
    type:"full time",
    jobtype:"remote",
    },{
        id:20 ,
    Company:"Angelist",
    worktype:"Consultancy",
    post:"Fullstack",
    location:"anywhere",
    type:"full time",
    jobtype:"remote",
    }]


export default Main